# Generated by Django 5.2.3 on 2025-06-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='image',
            field=models.ImageField(upload_to='plots/'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='plot',
            name='plot_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='plot',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
