# Generated by Django 5.2.3 on 2025-06-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0003_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='plot',
        ),
    ]
