# Generated by Django 5.2.3 on 2025-06-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0006_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('is_floating', models.BooleanField(default=False)),
            ],
        ),
    ]
