# Generated by Django 5.2.3 on 2025-06-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0007_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloatingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='floating/')),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='is_floating',
        ),
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
    ]
