# Generated by Django 5.2.3 on 2025-06-22 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0008_floatingvideo_remove_video_is_floating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_file',
            new_name='video',
        ),
        migrations.RemoveField(
            model_name='floatingvideo',
            name='video_file',
        ),
        migrations.AddField(
            model_name='floatingvideo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 22, 9, 29, 37, 597823, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floatingvideo',
            name='video',
            field=models.FileField(default=None, upload_to='floating_videos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='is_floating',
            field=models.BooleanField(default=False),
        ),
    ]
