# Generated by Django 5.2.3 on 2025-06-22 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0009_rename_video_file_video_video_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floatingvideo',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='video',
            name='is_floating',
        ),
    ]
