# Generated by Django 5.2.3 on 2025-06-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0010_rename_created_at_floatingvideo_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floatingvideo',
            name='title',
            field=models.CharField(default='Untitled Floating Video', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='Untitled Video', max_length=255),
            preserve_default=False,
        ),
    ]
