# Generated by Django 5.2.3 on 2025-06-22 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0011_floatingvideo_title_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='plots.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plot',
            name='size',
            field=models.CharField(default='5 Marla', max_length=100),
            preserve_default=False,
        ),
    ]
