# Generated by Django 5.2.3 on 2025-06-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0012_plot_project_plot_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='map_embed_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
