# Generated by Django 5.2.3 on 2025-06-22 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0013_project_map_embed_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('advance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining', models.DecimalField(decimal_places=2, max_digits=12)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='plots.project')),
            ],
        ),
    ]
