# Generated by Django 5.2.3 on 2025-06-23 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0014_installmentplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
