# Generated by Django 5.2.3 on 2025-06-24 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0016_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.JSONField()),
                ('description', models.TextField()),
                ('map_embed_url', models.TextField(blank=True, null=True)),
                ('plot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plots.plot')),
            ],
        ),
        migrations.CreateModel(
            name='PlotImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plot_detail_images/')),
                ('plot_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='plots.plotdetail')),
            ],
        ),
        migrations.CreateModel(
            name='PlotVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='plot_detail_videos/')),
                ('plot_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='plots.plotdetail')),
            ],
        ),
    ]
