# Generated by Django 5.2.3 on 2025-06-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0017_plotdetail_plotimage_plotvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotimage',
            name='image',
            field=models.ImageField(upload_to='plot_images/'),
        ),
        migrations.AlterField(
            model_name='plotvideo',
            name='video',
            field=models.FileField(upload_to='plot_videos/'),
        ),
    ]
