# Generated by Django 5.2.3 on 2025-06-25 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0018_alter_plotimage_image_alter_plotvideo_video'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plot',
            unique_together={('project', 'plot_number')},
        ),
    ]
