# Generated by Django 5.2.3 on 2025-06-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0019_alter_plot_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='plot_number',
            field=models.CharField(max_length=100),
        ),
    ]
