# Generated by Django 5.2.3 on 2025-06-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0020_alter_plot_plot_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentplan',
            name='installment',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
