# Generated by Django 5.2.3 on 2025-06-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0021_installmentplan_installment'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000000, max_digits=12),
            preserve_default=False,
        ),
    ]
