# Generated by Django 5.2.3 on 2025-06-27 05:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0022_plotdetail_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='master_plan_pdf',
            field=models.FileField(blank=True, null=True, upload_to='project_pdfs/'),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_plan_pdf',
            field=models.FileField(blank=True, null=True, upload_to='project_pdfs/'),
        ),
        migrations.AddField(
            model_name='project',
            name='price_range_max',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='price_range_min',
            field=models.CharField(default='PKR 0', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='Untitled Project', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProjectDescriptionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_sections', to='plots.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDescriptionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='plots.projectdescriptionsection')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='plots.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectOverviewRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_name', models.CharField(max_length=100)),
                ('price_range', models.CharField(max_length=100)),
                ('area_size', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overview_rows', to='plots.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='project_videos/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='plots.project')),
            ],
        ),
    ]
