# Generated by Django 5.2.3 on 2025-06-27 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0023_remove_project_description_project_master_plan_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFeatureGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_groups', to='plots.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFeaturePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='plots.projectfeaturegroup')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPlotType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255)),
                ('price_range', models.CharField(max_length=100)),
                ('area_size', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plot_types', to='plots.project')),
            ],
        ),
    ]
