# Generated by Django 5.2.3 on 2025-06-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0024_projectfeaturegroup_projectfeaturepoint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='master_plan_pdf',
        ),
        migrations.RemoveField(
            model_name='project',
            name='payment_plan_pdf',
        ),
        migrations.AddField(
            model_name='project',
            name='master_plan_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_plan_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
    ]
