# Generated by Django 5.2.3 on 2025-06-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0025_remove_project_master_plan_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('map_embed_url', models.URLField(blank=True)),
                ('image', models.ImageField(upload_to='other_plot_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='other_plot_videos/')),
                ('description', models.TextField()),
                ('overview', models.TextField()),
                ('available', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plot_size', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
