# Generated by Django 5.2.3 on 2025-06-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0026_otherplot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherplot',
            name='map_embed_url',
            field=models.URLField(max_length=1000),
        ),
    ]
