# Generated by Django 5.2.3 on 2025-06-28 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0027_alter_otherplot_map_embed_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherPlotImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='other_plots/images/')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='plots.otherplot')),
            ],
        ),
        migrations.CreateModel(
            name='OtherPlotVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='other_plots/videos/')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='plots.otherplot')),
            ],
        ),
    ]
