# Generated by Django 5.2.3 on 2025-06-29 03:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0028_otherplotimage_otherplotvideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installmentplan',
            old_name='installment',
            new_name='reference_id',
        ),
        migrations.RemoveField(
            model_name='installmentplan',
            name='project',
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='coupon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='installments',
            field=models.TextField(default='Monthly', help_text='e.g. Monthly: 20, Quarterly: 4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='plan_type',
            field=models.CharField(choices=[('project', 'Project'), ('other_plot', 'Other Plot')], default='project', max_length=20),
            preserve_default=False,
        ),
    ]
