# Generated by Django 5.2.3 on 2025-06-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0029_rename_installment_installmentplan_reference_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentplan',
            name='advance',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='installments',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='remaining',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='total_payment',
            field=models.CharField(max_length=100),
        ),
    ]
