# Generated by Django 5.2.3 on 2025-06-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0030_alter_installmentplan_advance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installmentplan',
            name='coupon',
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='ptype',
            field=models.CharField(default='residentail', max_length=100),
            preserve_default=False,
        ),
    ]
