# Generated by Django 5.2.3 on 2025-06-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0031_remove_installmentplan_coupon_installmentplan_ptype'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('project', 'Project'), ('other_plot', 'Other Plot')], max_length=20)),
                ('reference_id', models.IntegerField()),
                ('ptype', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('cnic', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
