# Generated by Django 5.2.3 on 2025-06-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0033_userbooking_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbooking',
            name='plot_number',
            field=models.CharField(default=222, max_length=100),
            preserve_default=False,
        ),
    ]
