# Generated by Django 5.2.3 on 2025-06-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0035_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='phone_number',
            field=models.CharField(default='00000000000', max_length=20),
            preserve_default=False,
        ),
    ]
