# Generated by Django 5.2.3 on 2025-06-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0036_dealer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherplot',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
